version: "3.0"
services:
  db:
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: work-logger
      POSTGRES_PASSWORD: work-logger
      POSTGRES_DB: work-logger
